In [46]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Salary_Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,1].values

# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [47]:
x_test

array([[  1.5],
       [ 10.3],
       [  4.1],
       [  3.9],
       [  9.5],
       [  8.7]])

In [44]:
x_train

array([[  1.5],
       [ 10.3],
       [  4.1],
       [  3.9],
       [  9.5],
       [  8.7],
       [  9.6],
       [  4. ],
       [  5.3],
       [  7.9],
       [  2.9],
       [  5.1],
       [  3.2],
       [  4.5],
       [  8.2],
       [  6.8],
       [  1.3],
       [ 10.5],
       [  3. ],
       [  2.2],
       [  5.9],
       [  6. ],
       [  3.7],
       [  3.2],
       [  9. ],
       [  2. ],
       [  1.1],
       [  7.1],
       [  4.9],
       [  4. ]])

In [39]:
y_train

array([  37731.,  122391.,   57081.,   63218.,  116969.,  109431.,
        112635.,   55794.,   83088.,  101302.,   56642.,   66029.,
         64445.,   61111.,  113812.,   91738.,   46205.,  121872.,
         60150.,   39891.,   81363.,   93940.,   57189.,   54445.,
        105582.,   43525.,   39343.,   98273.,   67938.,   56957.])

In [45]:
y_test

array([], dtype=float64)

In [32]:
X

array([], shape=(30L, 0L), dtype=float64)

In [23]:
y_test

array([], dtype=float64)

In [27]:
x_train

array([], shape=(30L, 0L), dtype=float64)

In [48]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [49]:
y_pred=regressor.predict(x_test)

In [50]:
y_pred

array([  40748.96184072,  122699.62295594,   64961.65717022,
         63099.14214487,  115249.56285456,  107799.50275317])

In [51]:
y_test

array([  37731.,  122391.,   57081.,   63218.,  116969.,  109431.])