In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [6]:
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 3] = labelencoder_X.fit_transform(X[:, 3])
onehotencoder = OneHotEncoder(categorical_features = [3])
X = onehotencoder.fit_transform(X).toarray()

In [4]:
X

array([[  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          1.65349200e+05,   1.36897800e+05,   4.71784100e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.62597700e+05,   1.51377590e+05,   4.43898530e+05],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.53441510e+05,   1.01145550e+05,   4.07934540e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          1.44372410e+05,   1.18671850e+05,   3.83199620e+05],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.42107340e+05,   9.13917700e+04,   3.66168420e+05],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          1.31876900e+05,   9.98147100e+04,   3.62861360e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.34615460e+05,   1.47198870e+05,   1.27716820e+05],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.30298130e+05,   1.45530060e+05,   3.23876680e+05],


In [25]:
X=X[:,1:]

In [26]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [27]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [28]:
y_pred=regressor.predict(X_train)

In [29]:
y_pred

array([  95764.42320496,   89164.62849777,  109506.72329085,
         91366.21889411,  127111.48666646,  159019.04337114,
        148905.9881254 ,   48179.60744027,   45374.34722507,
        102951.95967978,  145449.63178398,   96684.71387298,
         97535.3576194 ,  116571.15139255,   69421.13311312,
        116212.62095134,   60736.53267611,  152787.95464277,
        127413.03373111,  102210.16391827,  161822.7226407 ,
        131583.61511491,   75019.09161338,   48054.91969395,
        189547.28196894,  127528.92248422,   85540.50570955,
        111255.82514049,  156191.10124355,  108464.25100331,
         75306.81185049,  119915.38726755,  115144.58914953,
        152688.9067796 ,   81513.47163492,   57298.28613019,
        172852.28336637,  192919.57537463,   47007.62737751,
         65835.99435878])

In [30]:
y_train

array([  96778.92,   96479.51,  105733.54,   96712.8 ,  124266.9 ,
        155752.6 ,  132602.65,   64926.08,   35673.41,  101004.64,
        129917.04,   99937.59,   97427.84,  126992.93,   71498.49,
        118474.03,   69758.98,  152211.77,  134307.35,  107404.34,
        156991.12,  125370.37,   78239.91,   14681.4 ,  191792.06,
        141585.52,   89949.14,  108552.04,  156122.51,  108733.99,
         90708.19,  111313.02,  122776.86,  149759.96,   81005.76,
         49490.75,  182901.99,  192261.83,   42559.73,   65200.33])

In [4]:
import statsmodels.formula.api as sm

In [33]:
X=np.append(arr=np.ones((50,1)).astype(int),values=X,axis=1)

In [34]:
X

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   1.65349200e+05,   1.36897800e+05,
          4.71784100e+05],
       [  1.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.62597700e+05,   1.51377590e+05,
          4.43898530e+05],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   1.53441510e+05,   1.01145550e+05,
          4.07934540e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   1.44372410e+05,   1.18671850e+05,
          3.83199620e+05],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   1.42107340e+05,   9.13917700e+04,
          3.66168420e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   1.31876900e+05,   9.98147100e+04,
          3.62861360e+05],
       [  1.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.34

In [11]:
x_opt=X[:,[0,1,2,3,4,5,6]]

In [12]:
regressor_ols=sm.OLS(endog=y,exog=x_opt).fit()

In [14]:
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sun, 08 Jul 2018   Prob (F-statistic):           1.34e-27
Time:                        22:20:08   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.763e+04   5073.636      7.417      0.000    2.74e+04    4.79e+04
x1          1.249e+04   2449.797      5.099      0.000    7554.868    1.74e+04
x2          1.269e+04   2726.700      4.654      0.000    7195.596    1.82e+04
x3          1.245e+04   2486.364      5.007      0.000    7439.285    1.75e+04
x4             0.8060      0.046     17.369      0.000       0.712       0.900
x5            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x6             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     2.69e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.35e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [15]:
x_opt=X[:,[0,1,2,3,4,6]]
regressor_ols=sm.OLS(endog=y,exog=x_opt).fit()

In [16]:
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     215.8
Date:                Sun, 08 Jul 2018   Prob (F-statistic):           9.72e-29
Time:                        22:21:15   Log-Likelihood:                -525.53
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1071.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.525e+04   2100.376     16.782      0.000     3.1e+04    3.95e+04
x1          1.171e+04   1910.312      6.130      0.000    7861.854    1.56e+04
x2          1.185e+04   2170.903      5.459      0.000    7477.785    1.62e+04
x3          1.169e+04   1988.428      5.879      0.000    7684.996    1.57e+04
x4             0.7967      0.042     18.771      0.000       0.711       0.882
x5             0.0298      0.016      1.842      0.072      -0.003       0.062
==============================================================================
Omnibus:                       14.640   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.037
Skew:                          -0.938   Prob(JB):                     2.70e-05
Kurtosis:                       5.565   Cond. No.                     6.69e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 7.33e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [18]:
x_opt=X[:,[0,1,2,3,4]]
regressor_ols=sm.OLS(endog=y,exog=x_opt).fit()
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.943
Method:                 Least Squares   F-statistic:                     272.4
Date:                Sun, 08 Jul 2018   Prob (F-statistic):           2.76e-29
Time:                        22:21:59   Log-Likelihood:                -527.35
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      46   BIC:                             1070.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       3.686e+04   1959.786     18.806      0.000    3.29e+04    4.08e+04
x1          1.189e+04   1956.677      6.079      0.000    7955.697    1.58e+04
x2          1.306e+04   2122.665      6.152      0.000    8785.448    1.73e+04
x3           1.19e+04   2036.022      5.847      0.000    7805.580     1.6e+04
x4             0.8530      0.030     28.226      0.000       0.792       0.914
==============================================================================
Omnibus:                       13.418   Durbin-Watson:                   1.122
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               17.605
Skew:                          -0.907   Prob(JB):                     0.000150
Kurtosis:                       5.271   Cond. No.                     3.70e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.74e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [20]:
x_opt

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   1.65349200e+05],
       [  1.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.62597700e+05],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   1.53441510e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   1.44372410e+05],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   1.42107340e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   1.31876900e+05],
       [  1.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   1.34615460e+05],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   1.30298130e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   1.20542520e+05],
       [  1.00000000e+00,   1.0000000

In [23]:
y_pred=regressor_ols.predict(x_opt)

In [24]:
y_pred

array([ 189807.10614462,  187450.41249157,  180803.82484718,
        171913.39128786,  171135.5006604 ,  161254.41568055,
        163580.87746675,  161061.95573653,  151585.91235863,
        153958.26686051,  136848.813931  ,  134626.24187949,
        129982.53859488,  127222.35641087,  152228.98133801,
        146451.63493637,  115297.68870801,  129505.06725295,
        128178.74161265,  122478.31242611,  113797.0054356 ,
        115628.32985708,  113033.63362445,  107521.3640057 ,
        114480.6195739 ,  103911.1770733 ,  114171.83268496,
        110269.74112415,  106258.02625765,  104723.273755  ,
        102797.27192286,  100911.0221633 ,  102839.90631152,
         97252.1608626 ,   88353.17112791,   88011.27926645,
         74365.35266112,   86343.34314907,   66016.529919  ,
         81641.95004697,   73278.74474605,   73707.80729026,
         68916.88949801,   61986.96181715,   67668.75264574,
         49613.41558559,   51036.58395928,   48750.59806979,
         49222.57684081,

In [32]:
y

array([ 192261.83,  191792.06,  191050.39,  182901.99,  166187.94,
        156991.12,  156122.51,  155752.6 ,  152211.77,  149759.96,
        146121.95,  144259.4 ,  141585.52,  134307.35,  132602.65,
        129917.04,  126992.93,  125370.37,  124266.9 ,  122776.86,
        118474.03,  111313.02,  110352.25,  108733.99,  108552.04,
        107404.34,  105733.54,  105008.31,  103282.38,  101004.64,
         99937.59,   97483.56,   97427.84,   96778.92,   96712.8 ,
         96479.51,   90708.19,   89949.14,   81229.06,   81005.76,
         78239.91,   77798.83,   71498.49,   69758.98,   65200.33,
         64926.08,   49490.75,   42559.73,   35673.41,   14681.4 ])