In [23]:
import pyaudio
import wave
import librosa

FORMAT = pyaudio.paInt16
CHANNELS = 2
RATE = 44100
CHUNK = 1024
RECORD_SECONDS = 5
WAVE_OUTPUT_FILENAME = "file.wav"
 
audio = pyaudio.PyAudio()
 
# start Recording
stream = audio.open(format=FORMAT, channels=CHANNELS,
                rate=RATE, input=True,
                frames_per_buffer=CHUNK)
print ("recording...")
frames = []
 
for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
    data = stream.read(CHUNK)
    frames.append(data)
print ("finished recording")
 
stream.stop_stream()
stream.close()
audio.terminate()
 
waveFile = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
waveFile.setnchannels(CHANNELS)
waveFile.setsampwidth(audio.get_sample_size(FORMAT))
waveFile.setframerate(RATE)
waveFile.writeframes(b''.join(frames))
waveFile.close()


recording...
finished recording


In [50]:
################################ FINDING AMPLITUDE######################################## 
import numpy as np
CHUNK = 2**11  
RATE = 44100  
   
p = pyaudio.PyAudio()  
stream = p.open(format=pyaudio.paInt16, channels=1, rate=RATE, input=True,  
         frames_per_buffer=CHUNK)  
   
for i in range(int(10 * 44100 / 1024)):
# for i in range(int(1000)):
    data = np.frombuffer(stream.read(CHUNK), dtype=np.int16)  
    peak = np.average(np.abs(data)) * 2  
    bars = "-->" * int(50 * peak / 2**16)  
    print (data)
#     print(" %05d %s" % (peak, bars))   
stream.stop_stream()  
stream.close()  
p.terminate()  

[ -3  -4  -5 ... -13 -14 -16]
[-17 -18 -17 ...  -1  -1   1]
[ 3  5  3 ... -1 -3 -4]
[-1  3  6 ...  3 11 15]
[ 10  -5 -19 ...  18  14  16]
[26 36 39 ...  5  4  1]
[0 0 2 ... 5 6 8]
[ 13  17  20 ... -10 -10 -10]
[-9 -7 -7 ...  4  4  3]
[3 2 1 ... 6 6 6]
[6 7 6 ... 6 6 5]
[  5   4   1 ... -15 -17 -16]
[-13  -9  -6 ...  15  15  13]
[ 11  10  10 ... -10 -14 -18]
[-23 -30 -37 ...  -5   8  15]
[ 13   2 -13 ...  16  19  17]
[ 12   7   2 ... -24 -28 -34]
[-39 -43 -45 ...  16  17  18]
[ 18  17  11 ... -19 -16 -14]
[-10  -7  -5 ...  -7  -9  -9]
[-7 -5 -4 ...  5  4 -2]
[ -6  -9 -10 ...   2   3   4]
[ 5  4  3 ... -3 -3 -5]
[-4 -5 -5 ...  3  0 -3]
[ -7 -10 -11 ...  -2  -2  -3]
[-1  1  3 ... -2  0  3]
[ 5  6  6 ...  0  0 -1]
[ 0  1  1 ...  0 -3 -5]
[ -6  -8 -13 ...  -3  -3  -5]
[-6 -8 -9 ...  4  3  2]
[  2   2   1 ... -23 -20 -19]
[-18 -18 -18 ...   5   2   1]
[ 3  6  8 ...  8 14 17]
[  18   17   15 ...  663 1051 1397]
[1676 1879 2019 ... 2449 2433 2349]
[2184 1908 1507 ...  768 1288 1763]
[2139 2381

[ 10   9   6 ...  -2  -7 -10]
[ -9  -9  -8 ... -33 -29 -22]
[-16 -13 -14 ...   5   4   2]
[ 3  3  5 ... -6 -5 -5]
[ -6  -8 -11 ...  11  12  11]
[10  9 10 ... -2  1  4]
[ 7 10  9 ... -8 -5 -5]
[ -4  -6  -9 ... -16 -25 -24]
[-24 -37 -65 ...   8   2   5]
[ 17  26  28 ... -17 -22 -22]
[-15  -4   4 ...  15  11   7]
[ 4  1 -1 ...  0  2  4]
[ 5  5  2 ...  2  0 -3]
[-4 -5 -4 ...  9 10 11]
[11 10  6 ...  3  4  2]
[ 1 -2 -5 ...  7  4  3]
[ 3  6  9 ...  5  1 -2]
[ -1  -2  -4 ... -17 -18 -18]
[-18 -17 -17 ...   7  10  11]
[ 14  14  12 ... -19 -20 -19]
[-19 -19 -20 ...  -4  -7 -12]
[-16 -20 -20 ...   9  10  10]
[10  8  5 ... 11 10  8]
[10 12 16 ...  1  4  6]
[  7   5   1 ...  -6  -8 -11]
[-12 -12 -10 ...   5   6   8]
[10 13 14 ... 16 15 12]
[ 10   6   3 ... -40 -42 -44]
[-45 -46 -47 ...   3   2   0]
[ 1  1  1 ... 13 11  7]
[ 4  1 -1 ...  0 -1 -3]
[ -3  -5  -5 ...  -4  -7 -10]
[-12 -12 -12 ...  10  13  15]
[19 20 22 ... -8 -9 -7]
[-3  1  4 ... -4 -6 -8]
[-6 -3  0 ...  7  6  5]
[ 4  2 -1 ...  8  9  8

In [45]:
################################ PRODUCING WAVE######################################## 

import time
import pylab
import pyaudio
import numpy as np
RATE = 44100
CHUNK = int(RATE/20)

def soundplot(stream):
#     t1=time.time()
    data = np.frombuffer(stream.read(CHUNK),dtype=np.int16)
    pylab.plot(data)
    pylab.title(i)
    pylab.grid()
    pylab.axis([0,len(data),-2**16/2,2**16/2])
    pylab.savefig("03.png",dpi=200)
    pylab.close('all')
#     print("time %.02f ms"%((time.time()-t1)*1000))
    
if __name__=="__main__":
    p=pyaudio.PyAudio()
    stream=p.open(format=pyaudio.paInt16,channels=1,rate=RATE,input=True,
                  frames_per_buffer=CHUNK)
    for i in range(int(20*RATE/CHUNK)):
        soundplot(stream)
    stream.stop_stream()
    stream.close()
    p.terminate()

SyntaxError: invalid syntax (<ipython-input-12-4846f4a5248f>, line 71)

In [49]:
################################ FINDING FREQUNCY######################################## 

import pyaudio
import numpy as np
np.set_printoptions(suppress=True)
CHUNK = 4096 #data points to read
RATE = 44100 #time resolution
TARGET = 2100 #show this frequency

p=pyaudio.PyAudio()
stream=p.open(format=pyaudio.paInt16,channels=1,rate=RATE,input=True,
              frames_per_buffer=CHUNK)
for i in range(int(10* 44100/1024)):
    data = np.fromstring(stream.read(CHUNK),dtype=np.int16)
    fft = abs(np.fft.fft(data).real)
    fft = fft[:int(len(fft)/2)] # keeponly first half
    freq = np.fft.fftfreq(CHUNK,1.0/RATE)
    freq = freq[:int(len(freq)/2)] #only first half
    assert freq[-1]>TARGET, "ERROR: increase chunk size"
    val = fft[np.where(freq>TARGET)[0][0]]
    if val >1000:
        print(val)

stream.stop_stream()
stream.close()
p.terminate()

C:\Users\Deepanshi Bansal\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  app.launch_new_instance()


1858.437069407555
1125.9219704083703
1690.3346807692228
2091.4437173899832
2304.9704407163053
1375.7608958898402
1075.7012558369677
1118.0231828487472
1307.317649590975
1053.6160902419156
1921.663444769537
2220.322909622867
1448.0430663520497
1831.5468448098072
1388.6137286225467
2027.096730750228
1738.2249108360643
1769.4135828724054
1585.4519919102777
1081.547094318849
2543.7835812739086
1399.9499534322522
1751.846068727552
1993.7228607379152
2502.2537578530037
1286.3626491358325
1740.4611463322442
1993.7212202739856
3069.074570486814
1548.8141846649357
3465.3747783600816
1113.090193023976
2660.01224548558
1453.0153912383007
1422.6761023085355
1848.338102956074
1866.748474382919
1920.059625119026
1473.1920275405946
1781.2618633123243
1194.257951844656
1733.2050561453625
2092.3915328249345
1764.7514796339094
1648.437036815932
1299.903069887795
1099.6102942111754
1564.61124320729
1381.58248589213
2744.0760325697397
1642.2729902635465
1622.5435560500368
1301.8505194135864
2278.942352633

In [39]:
import pyaudio
import numpy as np
CHUNK = 4096 #data points to read
RATE = 44100 #time resolution
TARGET = 2100 #show this frequency
p=pyaudio.PyAudio()
stream=p.open(format=pyaudio.paInt16,channels=1,rate=RATE,input=True,
              frames_per_buffer=CHUNK)
for i in range(int(10* 44100/1024)):
    data = np.fromstring(stream.read(CHUNK),dtype=np.int16)
    D=librosa.feature.melspectrogram(y=data,sr=RATE) 
    log_power=librosa.power_to_db(np.abs(D)**2)
    print (log_power)

C:\Users\Deepanshi Bansal\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  # Remove the CWD from sys.path while we load stuff.


ParameterError: data must be floating-point

In [9]:
from pyAudioAnalysis import audioSegmentation as aS


ModuleNotFoundError: No module named 'hmmlearn'

In [ ]:
[flagsInd, classesAll, acc, CM] = aS.mtFileClassification("data/scottish.wav", "data/svmSM", "svm", True, 'data/scottish.segments')
