In [1]:
x=4
y=6
x+y

10

In [2]:
'deepanshi'+'bansal'

'deepanshibansal'

In [3]:
x={1,2,3,4,'tuple',5}


In [4]:
y=[1,2,3,4,5,'list',6]

In [5]:
str='this is a string'

In [11]:
X={'DEEPANSHI':'BANSAL','SPARSH':'WADHWA','DEEPALI':'SINGHAL'}
X['VIVEK']='AGARWAL'
for n,surname in X.items():
    print(n+" "+surname)

DEEPANSHI BANSAL
SPARSH WADHWA
DEEPALI SINGHAL
VIVEK AGARWAL


In [16]:
z=('deepanshi','btech','mait')
name,degree,clg=z
name

'deepanshi'

In [17]:
clg

'mait'

In [18]:
degree

'btech'

In [19]:
type(z)

tuple

In [20]:
q={1,2,3,4,'tuple'}

In [21]:
type(q)

set

In [23]:
a={'person':'deepanshi','clg':'mait','degree':'btech'}
statement='{} is studying in {} for the degree of {}'
print(statement.format(a['person'],a['clg'],a['degree']))

deepanshi is studying in mait for the degree of btech


In [1]:
'deepanshi is'+str(2*2*2*2)+'yrs old'

'deepanshi is16yrs old'

In [3]:
import csv
%precision 2
with open('./mpg.csv') as csvfile:
    mpg=list(csv.DictReader(csvfile))

In [31]:
import time as tym
import datetime as date


In [33]:
tym.time()

1510492179.44

In [50]:
datenow=date.datetime.fromtimestamp(tym.time())
datenow

datetime.datetime(2017, 11, 12, 18, 43, 6, 213000)

In [59]:
datenow.year
datenow.month
datenow.minute
datenow.second

6

In [66]:
dt=date.date.today()
dt

datetime.date(2017, 11, 12)

In [67]:
date.datetime.fromtimestamp(tym.time())

datetime.datetime(2017, 11, 12, 21, 45, 30, 845000)

In [94]:
people = ['Dr. Christopher Brooks', 'Dr. Collins-Thompson', 'Dr. VG  Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return '{} {}'.format(title, lastname)

list(map(split_title_and_name, people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [96]:
import numpy as np

In [99]:
my=np.array([1,3,6])
my

array([1, 3, 6])

In [130]:
my=np.arange(0,36,1)
n=my.reshape(6,6)
n.reshape(36)[::7]
n[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [116]:
my

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [107]:
 ['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]